### ISSUE TITLE
Jenkins build API return wrong `result`

### ISSUE THREAD

**Issue by wuhuizuo** [PingCAP-QE/ci#2186]
ref: https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_check2/detail/ghpr_check2/23393/pipeline

It failed but the prow's  jenkins-operator component got `succcess` from jenkins controller API. 

It's maybe a issue in jenkins controller.

**Comment by wuhuizuo** [comment]
Also happened in https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_check2/23731/:

```yaml
startTime: "2023-06-29T09:11:18Z"
pendingTime: "2023-06-29T09:11:52Z"
completionTime: "2023-06-29T09:20:20Z"
build_id: "1674344921957404672"
description: Jenkins job succeeded.
jenkins_build_id: "23731"
pod_name: e872de4c-165c-11ee-868d-fe60009d0287
prev_report_states:
  gcsreporter: success
  github-reporter: success
state: success
url: https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_check2/23731/display/redirect
```

the realtime cost is 25 minutes
